//! Compiles the UI, and hands the app's names from `Cargo.toml` (the
//! product name and identifier in `[package.metadata.packager]`) to the
//! code: `APP_NAME` and `APP_ID` for Rust (see `src/app.rs`), and the
//! `AppInfo` global for Slint (`import { AppInfo } from "@app-info";`).

use std::collections::HashMap;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    let (name, id) = app_names(&manifest_dir.join("Cargo.toml"));
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rustc-env=APP_NAME={name}");
    println!("cargo:rustc-env=APP_ID={id}");
    let app_info = out_dir.join("app_info.slint");
    let slint = format!(
        "// Generated by build.rs from Cargo.toml.\nexport global AppInfo {{\n    out property <string> name: \"{name}\";\n}}\n"
    );
    std::fs::write(&app_info, slint).expect("write app_info.slint");
    let libraries = HashMap::from([("app-info".to_owned(), app_info)]);
    let config = slint_build::CompilerConfiguration::new().with_library_paths(libraries);
    slint_build::compile_with_config("ui/app.slint", config).expect("compile ui/app.slint");
}

/// The product name and identifier from `[package.metadata.packager]`, checked.
fn app_names(manifest: &Path) -> (String, String) {
    let text = std::fs::read_to_string(manifest).expect("read Cargo.toml");
    let manifest: toml::Table = text.parse().expect("parse Cargo.toml");
    let packager = manifest
        .get("package")
        .and_then(|package| package.get("metadata"))
        .and_then(|metadata| metadata.get("packager"))
        .expect("[package.metadata.packager] in Cargo.toml");
    let name = packager.get("product-name").and_then(toml::Value::as_str).expect("product-name").to_owned();
    let id = packager.get("identifier").and_then(toml::Value::as_str).expect("identifier").to_owned();
    // Both go into strings as they are: Slint, desktop entries, D-Bus.
    assert!(
        !name.is_empty() && name.len() <= 64 && name.chars().all(|c| c.is_alphanumeric() || c == ' '),
        "product-name {name:?}: letters, digits and spaces only"
    );
    assert!(is_reverse_dns(&id), "identifier {id:?}: a reverse-DNS name, as D-Bus and desktop entries need");
    (name, id)
}

/// A D-Bus well-known name that's also a valid interface name and desktop
/// file id: two or more dot-separated elements of ASCII letters, digits and
/// `_`, none starting with a digit.
fn is_reverse_dns(id: &str) -> bool {
    let valid_element = |element: &str| {
        !element.is_empty()
            && !element.starts_with(|c: char| c.is_ascii_digit())
            && element.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
    };
    id.len() <= 255 && id.split('.').count() >= 2 && id.split('.').all(valid_element)
}
